### ISSUE TITLE
Ability to suppress NotSupportedException for reference linkbases

### ISSUE THREAD

**Issue by tmcg** [JeffFerguson/gepsio#13]
Hi, I'm attempting to parse some [Standard Business Reporting](http://www.sbr.gov.au/) XBRL messages from the Australian Taxation Office but it's failing with NotSupportedException during taxonomy schema validation.  If I comment out the exception and recompile, I have no trouble accessing the document contexts and facts.

Their taxonomy commonly uses reference linkbases to point to specific articles of tax legislation, which I'm not interested in and should be ok to ignore for my use case. e.g [activity statements lodgement message schema](http://sbr.gov.au/taxonomy/sbr_au_reports/ato/as/as_0001/as.0001.list.response.02.00.report.xsd)

A proposal might be for Gepsio to pass an "XbrlDocumentParseOptions" to the XbrlDocument that can selectively disable that exception. I could submit an example pull request if it's a good idea?

**Comment by JeffFerguson** [comment]
Hello! I'd like to understand the issue a bit better. Would it be possible to attach a copy of the XBRL that you're trying to parse in a reply so that I can take a closer look?

Thank you for the report!

**Comment by tmcg** [comment]
Hi! thanks for the quick reply

The list response XBRL document is attached - it's public data as part of the ATO conformance testing suite for calling the GST business activity statement lodgement service.

[CONF-ATO-AS-001_List_Response_03.xml](https://github.com/JeffFerguson/gepsio/files/2191568/CONF-ATO-AS-001_List_Response_03.xml.txt)

The ATO has an [SBR Taxonomy Viewer](https://www.taxonomy-collaboration.sbr.gov.au/yeti/resources/yeti-gwt/Yeti.jsp) online if that helps also.
The ATO is just a small part of the AU government's Standard Business Reporting web services portal, so for this particular document you just need to drill down into where they're located:
SBR AU -> 1. Current Version -> SBR AU 2018.02.86 -> ATO Activity Statement

**Comment by JeffFerguson** [comment]
A ha! It seems that you have run into this code in `LinkbaseDocumentCollection.cs`:

```
else if (xlinkNode.IsInRole(XbrlDocument.XbrlReferenceLinkbaseReferenceRoleNamespaceUri) == true)
{
    throw new NotSupportedException("No support for reference linkbases.");
}
```

Sounds like I need to go find that part of the spec and implement that!

Thank you for the report! I will leave this issue open while I build out that support.

**Comment by tmcg** [comment]
Yep, that's the code. In the meantime I've commented out the exception and rebuilt as the legislation references are not critical. Thanks!

**Comment by tmcg** [comment]
brilliant, thanks I'll take a look

**Comment by JeffFerguson** [comment]
No worries. It's in the `develop` branch at the moment, and it will be pushed to `master` and an updated NuGet package released at the beginning of August.
