### ISSUE TITLE
Decimal Conversions Do Not Use Invariant Culture

### ISSUE THREAD

**Issue by JeffFerguson** [JeffFerguson/gepsio#16]
Bug report from a comment on [Issue 12](https://github.com/JeffFerguson/gepsio/issues/12):

> For instance you provided "https://.../msft-20111231.xml", Gepsio throws an exception while converting "1.0200" to decimal in CalculationArc.cs\CalculationArc(INode CalculationArcNode).
> This happens because of dot seperator.
> Solution: Use Convert.ToDecimal(OrderString, System.Globalization.CultureInfo.InvariantCulture);
> After making this changes, Gepsio works fine and shows labels for instance you provided.

Gepsio should be checked to ensure that all decimal conversions use invariant culture settings.

**Comment by cjundt** [comment]
Fixed in pull request #30.
