### ISSUE TITLE
[FIX] Crash when where is no internet connection available on host machine

### ISSUE THREAD

**Issue by panthernet** [JeffFerguson/gepsio#21]
Sorry have no possibility to make a pull right now.
Location: **XbrlSchema.cs** line **184**
Problem code:
`if(webResponse.StatusCode == HttpStatusCode.NotFound)`

You have to check **webResponse** for null or it will crash in the described case.
FInal fix should be:
`if(webResponse == null || webResponse.StatusCode == HttpStatusCode.NotFound)`

**Comment by JeffFerguson** [comment]
Thank you for the report! Should be an easy fix that I can make this weekend.

**Comment by cjundt** [comment]
Fixed in pull request #32.
