### ISSUE TITLE
Test case ExecuteXBRLCONF20141210Testcases is failing

### ISSUE THREAD

**Issue by cjundt** [JeffFerguson/gepsio#29]
Test case is failing on **develop** branch following v2.1.0.14 :

Message: Assert.Fail failed. 
Instance: 320-00-BindCalculationInferPrecision-instance.xbrl
Name: v00-CalculationWithPrecision3-Consistent
Description: 320.00 - Valid

Validation Error Type: JeffFerguson.Gepsio.SummationConceptValidationError
Validation Error Description: Fact A is based on an element that is named as the summation concept in a calculation link. The fact's value, after rounding, is 1600; however, the sum of the values of the contributing concepts, after rounding, is 1000. These values do not match; therefore, the rule specified by the fact's calculation link has been broken.

**Comment by cjundt** [comment]
Still failing on v2.1.0.15.

**Comment by JeffFerguson** [comment]
This is by design, and why Gepsio is a 2.1.0.* and not a 2.1.1.0 version (the initial 2.1 matches the version of the XBRL spec that is supports). The vision for Gepsio's versioning -- and I apologize for not making this more clear -- is that the versioning stays 2.1.0.* until it can pass all of the tests in the XBRL conformance suite. Once it is 2.1 compliant, then my idea was to move Gepsio's versioning to 2.1.1.0. I will continue to work on compatibility issues until all of the conformance tests pass.

Does that help clarify things?

**Comment by cjundt** [comment]
Yes, it's clear now.
I was a bit confused because I'm used to running unit tests as regression tests.
I occasionaly do TDD but tag failing "work in progress" tests as to be ignored until work is done.

A list of yet unsupported XBRL specs would be helpfull for people to contribute.

On my branch "29", I sorted out passing from failing conformance tests. If you find it usefull I can make it clean and submit a pull request ?

**Comment by JeffFerguson** [comment]
I'm glad you called it out. I added a bit to the Wiki page at [https://github.com/JeffFerguson/gepsio/wiki/Version-Numbering-Scheme](https://github.com/JeffFerguson/gepsio/wiki/Version-Numbering-Scheme) to attempt to explain this further.

Tell me more about this branch "29" that you have. Do you mean a branch for Issue 29?

**Comment by cjundt** [comment]
Yes, originally it was a branch to fix issue 29. 
I thought I would only have a few failing tests due to my configuration.

For this moment, I only managed to split the big bulk test into smaller groups of per category tests.
I also changed code in order to log and continue in case of failing test in a batch.
Finally, I tagged passing and failing test cases to sort things out.

**Comment by JeffFerguson** [comment]
Thank you! I'd be interested in taking a look at how you have organized things. Is there a pull request for it yet?

**Comment by cjundt** [comment]
Done!
Pull request #36

**Comment by jnettleton** [comment]
Looks like this test case should be fixed.

INVALID TEST CASE
..\..\..\XBRL-CONF-2014-12-10\Common\300-instance\301-04-IdScopeContextRefToUnit.xml
INVALID
    <example:fixedAssets precision="4" **contextRef="u1"** unitRef="u1">5000</example:fixedAssets>
VALID
    <example:fixedAssets precision="4" **contextRef="ci1"** unitRef="u1">5000</example:fixedAssets>
