### ISSUE TITLE
Linkbase node has unsupported child node with local name arcroleRef in document

### ISSUE THREAD

**Issue by andDev123** [JeffFerguson/gepsio#44]
Hi,

I'm just starting to look at xbrl parsing so presumably I'm doing something wrong. Got the below error while trying to parse an xbrl instance file that is supposed to follow the resol.xsd schema. Is this taxonomy / schema not supported by gepsio framework or is it something with the instance file ?

System.NotSupportedException: 'Linkbase node has unsupported child node with local name arcroleRef in document resol-find-prec.xml at URI file:///.../FullTaxonomy/www.eba.europa.eu/eu/fr/xbrl/crr/fws/res/cp-2017-15/2018-07-31/mod/resol.xsd.'

@Linkbasedocument.cs line 68

and the resol-find-prec.xml line the parser doesn't like is below:

  <link:arcroleRef arcroleURI="http://xbrl.org/arcrole/2008/variable-set-precondition" xlink:type="simple" xlink:href="http://www.xbrl.org/2008/variable.xsd#variable-set-precondition" />

**Comment by JeffFerguson** [comment]
Can you attach a copy of the XBRL document instance that you're trying to parse?

**Comment by andDev123** [comment]
Hi,
It's sensitive data so I can't attach it. However I managed to parse the same xbrl file using:
https://www.nuget.org/packages/Xbrl/
and
https://www.nuget.org/packages/Diwen.Xbrl/
