### ISSUE TITLE
How to attach label for a fact ?

### ISSUE THREAD

**Issue by ValeriyTitov** [JeffFerguson/gepsio#5]
How to find human-friendly name for a fact ?
Can you provide an example ?

**Comment by JeffFerguson** [comment]
The `FactCollection` class has methods like `GetFactByName()` and `GetFactsByName()`. Would those help? The `FactCollection` is available from an `XbrlFragment`, so the code would look something like this:

```
var xbrlDoc = new XbrlDocument();
xbrlDoc.Load("MyFile.xml");
var firstFragment = xbrlDoc.XbrlFragments[0];
var singleFact = firstFragment.Facts.GetFactByName("FactToFind");
```

or

```
var xbrlDoc = new XbrlDocument();
xbrlDoc.Load("MyFile.xml");
var firstFragment = xbrlDoc.XbrlFragments[0];
var allFactsMatchingName = firstFragment.Facts.GetFactsByName("FactToFind");
```

Does that help?

**Comment by ValeriyTitov** [comment]
I mean label for a fact, not its name. 
I don't understand how find Label for a fact in LabelLinkbase

**Comment by JeffFerguson** [comment]
Let me make sure that I understand what you're asking. I'd like to understand your need a bit more. Are you saying that ...

- for each label in a label linkbase, you want to find the fact for the label?

or

- for each fact in the document, find its label?

**Comment by ValeriyTitov** [comment]
The second one. 
> for each fact in the document, find its label?

For each fact, find its label with specific language(culture)

**Comment by JeffFerguson** [comment]
Let me think on that one a bit and get back to you. I'll come back with some sample code. Is there a specific XBRL document out on the Internet that you're working with? If there is, and you can send me the URL, I can use it in the example.

**Comment by ValeriyTitov** [comment]
Sure, but instance-file is useless without taxonomy.
[Accountants List.zip](https://github.com/JeffFerguson/gepsio/files/1856378/Accountants.List.zip)

Taxonomy is located at [Russian Central Bank](http://cbr.ru/Content/Document/File/36127/final_1_2.zip)

However, it local taxonomy.
I've overrided your XbrlSchema.GetFullSchemaPath with this ugly code just to make sure Gepsio able to load instance document.

```
string RealFileName;
                RealFileName = System.IO.Path.GetFileName(SchemaFilename);
                 if (RealFileName.Equals("ep_nso_purcb_m_q_30d.xsd", StringComparison.OrdinalIgnoreCase))
                {
                    FullPath = @"C:\Tax\www.cbr.ru\xbrl\nso\purcb\rep\2018-02-28\ep\ep_nso_purcb_m_q_30d.xsd";
                    return FullPath;
                }

```
I'm planning to use XmlUrlResolver next:)

**Comment by ValeriyTitov** [comment]
Most of labels will require cyrillic font. They probably look like chinese to you :)

**Comment by JeffFerguson** [comment]
Thank you! I will take a look at this and get back to you.

**Comment by JeffFerguson** [comment]
There is a sample available in [Issue 12](https://github.com/JeffFerguson/gepsio/issues/12).
