### ISSUE TITLE
No Support for xsd:import in Schema Handling

### ISSUE THREAD

**Issue by JeffFerguson** [JeffFerguson/gepsio#50]
### Discussed in https://github.com/JeffFerguson/gepsio/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **cjundt** April 15, 2024</sup>
Hi,

I'm working on new ESRS taxonomy (https://xbrl.efrag.org/taxonomy/draft-esrs/2023-07-31/esrs_all.xsd), which is using xsd:import feature. This is not implemented in Gepsio and thus most of the label linkbases are missing.
I'm not shure how to implement this because XmlSchema is already partly handling it, have you any idea ?</div>

**Comment by cjundt** [comment]
Fixed by PR #55

**Comment by JeffFerguson** [comment]
I'm so terribly sorry I am so late in approving this one. I'll do my best to improve. Thank you very much!
